[Variables]
Scale=230

Language=Your Language
Unit=f
Format=#I
Hidden=1
Hidden2=0
Player=WMP

Color1=25,25,25
Color2=43,43,43
Color3=255,255,255
Color4=37,37,37
Color5=3,125,254
Color6=255,255,255

SkinSize=0.9

TimeOfDay2="00":"Good night","01":"Good night","02":"Good night","03":"Good night","04":"Good night","05":"Good night","06":"Good night","07":"Good morning","08":"Good morning","09":"Good morning","10":"Good morning","11":"Good morning","12":"Good afternoon","13":"Good afternoon","14":"Good afternoon","15":"Good afternoon","16":"Good afternoon","17":"Good afternoon","18":"Good evening","19":"Good evening","20":"Good evening","21":"Good night","22":"Good night","23":"Good night"

TimeOfDay3="00":"Another Day","01":"Time to","02":"Deep in","03":"Quiet night","04":"Night fades","05":"Dawn is","06":"Embrace the","07":"Morning begins","08":"Time to Rise","09":"Its the day,","10":"Keep moving","11":"Almost middle","12":"Pause &","13":"Fresh focus","14":"Its Lunch","15":"Keep it","16":"Energy dips,","17":"Workday winding","18":"Go out,","19":"Evening calm","20":"Dine &","21":"Relax,","22":"Ready for","23":"Its Time to"

TimeOfDay4="00":"Ends","01":"Dream","02":"rest","03":"whispers","04":"away","05":"near","06":"sunrise","07":"now","08":"& shine","09":"Seize it","10":"forward","11":"hustle","12":"recharge","13":"begins","14":"time","15":"going","16":"push","17":"down","18":"Touch grass","19":"sets","20":"unwind","21":"the night","22":"dreaming?","23":"sleep :D"
CurrentTheme=Dark
